# Generated by Django 4.2.6 on 2023-10-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_initial'),
    ]

    operations = [
    ]
